"""Initial schema.

Revision ID: 0001
Revises:
Create Date: 2026-01-01

The first revision builds the schema straight from the mapped metadata. For revision one
that is strictly better than a hand-transcribed DDL dump: it cannot drift from the models
it is supposed to create, and it keeps the partial indexes and check constraints declared
on the models. Every subsequent revision is a normal autogenerated diff against this
baseline.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.db.models import Base

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
